### ISSUE TITLE
Multi sample support for CSV

### ISSUE THREAD

**Issue by supreme-gg-gg** [supreme-gg-gg/pendulum-tracking#7]
In plotting.py, support multiple processing for CSV so user not only need to run it on multiple video in a directory but also multiple csv directly with plotting functions. 

Should be easy, low priority.

**Comment by UDAYA-0504** [comment]
hiii there, i wannna try this

**Comment by UDAYA-0504** [comment]
hii i have updated your code kindly check my pull request

**Comment by supreme-gg-gg** [comment]
Merged and closing it now, thanks for the contribution.
